In [1]:
#numpy means numerical python
import numpy as np

# 1D array

In [2]:
array1 = np.arange(50)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [17]:
list2 = [2,4,6,8,]
array2 = np.array(list2)
array2

array([2, 4, 6, 8])

In [8]:
array5 = np.random.randn(6)
array5

array([ 0.34789839,  1.41218123, -0.88490222, -0.05593625,  1.17393743,
        0.4316042 ])

# 2D array

In [6]:
array3 = np.random.randn(2,3)   #(rows , colimns)
array3

array([[-2.1806469 ,  1.28898509, -0.42253224],
       [ 1.50475452,  0.89889642, -0.15126861]])

# 3D array

In [7]:
array4 = np.random.randn(4,2,3)   #(items , rows ,columns)
array4

array([[[ 2.33762756,  0.39336643, -0.70908316],
        [ 0.01692596, -1.48652649, -1.29342965]],

       [[-0.81801454, -0.02370169,  1.57842801],
        [ 0.91793327, -1.35025743,  0.77344735]],

       [[-2.00526786,  0.06790794, -0.62344775],
        [ 0.33729718,  0.56050814,  1.57969331]],

       [[ 0.1841844 , -0.65153751, -0.76459939],
        [ 0.65420005, -0.06830797, -0.16204432]]])

# properties of arrays

In [18]:
array4.shape

(4, 2, 3)

In [20]:
array3.dtype


dtype('float64')

In [22]:
array4.ndim


3

# special properties

In [23]:
np.empty((2,3,4))

array([[[2.33762756, 0.39336643, 0.70908316, 0.01692596],
        [1.48652649, 1.29342965, 0.81801454, 0.02370169],
        [1.57842801, 0.91793327, 1.35025743, 0.77344735]],

       [[2.00526786, 0.06790794, 0.62344775, 0.33729718],
        [0.56050814, 1.57969331, 0.1841844 , 0.65153751],
        [0.76459939, 0.65420005, 0.06830797, 0.16204432]]])

In [ ]:
np.zeros((4,2,3))

In [26]:
np.ones((6,1,2))

array([[[1., 1.]],

       [[1., 1.]],

       [[1., 1.]],

       [[1., 1.]],

       [[1., 1.]],

       [[1., 1.]]])

# airthemetic operations

In [25]:
array2*4

array([ 8, 16, 24, 32])

In [24]:
array2 + array2

array([ 4,  8, 12, 16])

In [11]:
1/array3

array([[-0.45857952,  0.77580416, -2.36668332],
       [ 0.66456022,  1.11247523, -6.61075682]])

# Logical operator

In [28]:
list6 = [5,10,2,4,20]
array6 = np.array(list6)
array6

array([ 5, 10,  2,  4, 20])

In [29]:
list2 = [2,4,6,8,10]
array2 = np.array(list2)
array2

array([ 2,  4,  6,  8, 10])

In [30]:
array2 > array6

array([False, False,  True,  True, False])

# slicing

In [32]:
array2[2]

6

In [33]:
array2[1:5]

array([ 4,  6,  8, 10])

In [34]:
array2[:2]

array([2, 4])

In [35]:
array3[1]

array([ 1.50475452,  0.89889642, -0.15126861])

In [36]:
array3[0][1]   #[rows][columns]

1.2889850905805103

In [37]:
array4[2]

array([[-2.00526786,  0.06790794, -0.62344775],
       [ 0.33729718,  0.56050814,  1.57969331]])

In [38]:
array4[2][0]

array([-2.00526786,  0.06790794, -0.62344775])

In [39]:
array4[2][0][2]

-0.6234477476132838

# indexing

In [40]:
array2[1:4]=10
array2

array([ 2, 10, 10, 10, 10])

In [45]:
array3[0]=100
array3

array([[100.        , 100.        , 100.        ],
       [  1.50475452,   0.89889642,  -0.15126861]])

In [43]:
xyz = array6[2:6]
xyz

array([ 2,  4, 20])

In [44]:
array6[:]=20
array6

array([20, 20, 20, 20, 20])

# fancy indexing

In [47]:
array7 = np.empty((8,4))
for i in range(8):
      array7[i] = i
array7

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [48]:
array8 = np.arange(50).reshape(5,10)
array8

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [49]:
array4.sort()
array4

array([[[-0.70908316,  0.39336643,  2.33762756],
        [-1.48652649, -1.29342965,  0.01692596]],

       [[-0.81801454, -0.02370169,  1.57842801],
        [-1.35025743,  0.77344735,  0.91793327]],

       [[-2.00526786, -0.62344775,  0.06790794],
        [ 0.33729718,  0.56050814,  1.57969331]],

       [[-0.76459939, -0.65153751,  0.1841844 ],
        [-0.16204432, -0.06830797,  0.65420005]]])

In [50]:
np.save("MY_Array",array4)

In [54]:
np.load("MY_Array.npy")

array([[[-0.70908316,  0.39336643,  2.33762756],
        [-1.48652649, -1.29342965,  0.01692596]],

       [[-0.81801454, -0.02370169,  1.57842801],
        [-1.35025743,  0.77344735,  0.91793327]],

       [[-2.00526786, -0.62344775,  0.06790794],
        [ 0.33729718,  0.56050814,  1.57969331]],

       [[-0.76459939, -0.65153751,  0.1841844 ],
        [-0.16204432, -0.06830797,  0.65420005]]])

In [55]:
array5.sort()
array5

array([-0.88490222, -0.05593625,  0.34789839,  0.4316042 ,  1.17393743,
        1.41218123])